# Get comments by post id
GET http://localhost:3333/api/posts/e203b269-4b66-4e3f-acd3-7ce25e9828f6 HTTP/1.1
Content-Type: application/json

###

# Create comment
POST http://localhost:3333/api HTTP/1.1
Content-Type: application/json

{
  "text": "Hello, World!",
  "authorId": "e203b269-4b66-4e3f-acd3-7ce25e9828f5",
  "postId": "e203b269-4b66-4e3f-acd3-7ce25e9828f6"
}

###

# Delete comment
DELETE http://localhost:3333/api/c4edfa58-1b35-4372-af9d-9915cc894c8c HTTP/1.1
Content-Type: application/json
