@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjliODQ3MzMzN2ZjMzhhMjkxMWRkZiIsImVtYWlsIjoiam9obkBlbWFpbC5jb20iLCJpYXQiOjE2NzMzOTE5NjIsImV4cCI6MTY3MzM5MjI2Mn0.ARjgGQCR4OyBGP0ktDIHnArgyVYbNpmqLQ4rMqK3iaw

###

# Get posts
GET http://localhost:3333/api/?sortByLikes=desc&sortByPublish=asc&postCategory=link HTTP/1.1
Content-Type: application/json

###

# Search posts
GET http://localhost:3333/api/search?title=Holidays HTTP/1.1
Content-Type: application/json

###

# Create text post
POST http://localhost:3333/api/text HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "A progressive Node.js framework",
  "text": "A complete development kit for building scalable server-side apps. Contact us to find out more about expertise consulting, on-site enterprise support, trainings, and private sessions.",
  "previewText": "A complete development kit for building scalable server-side apps. Contact us..."
}

###

# Update text post
PATCH http://localhost:3333/api/text/56 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "previewText": "A complete development kit for building scalable server-side apps. Contact us to find...",
  "tags": ["nextjs"]
}

###

# Create video post
POST http://localhost:3333/api/video HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "NestJs JWT - Access Tokens & Refresh Tokens",
  "video": "https://www.youtube.com/watch?v=uAKzFhE3rxU"
}

###

# Update video post
PATCH http://localhost:3333/api/video/57 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Holidays!!!!!!!!!!!!!!!!!!!"
}

###

# Create photo post
POST http://localhost:3333/api/photo HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{accessToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="avatar.jpg"
Content-Type: image/jpg

< /mnt/f/assets/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Update photo post
PATCH http://localhost:3333/api/photo/58 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
}

###

# Create quote post
POST http://localhost:3333/api/quote HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "text": "With software there are only two possibilities: either the users control the programme or the programme controls the users. If the programme controls the users, and the developer controls the programme, then the programme is an instrument of unjust power.",
  "quoteAuthor": "Richard Stallman"
}

###

# Update quote post
PATCH http://localhost:3333/api/quote/59 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "text": "With With software there are only two possibilities: either the users control the programme or the programme controls the users. If the programme controls the users, and the developer controls the programme, then the programme is an instrument of unjust power."
}

###

# Create link post
POST http://localhost:3333/api/link HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "link": "http://site.com/content/some-content",
  "description": "Информация о скидках"
}

###

# Update link post
PATCH http://localhost:3333/api/link/60 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "link": "https://site.com/content/some-content",
  "description": "Информация о скидках"
}

###

# Delete post
DELETE http://localhost:3333/api/60 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# Repost post
POST http://localhost:3333/api/2/repost HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# Set like
POST http://localhost:3333/api/59/like/true HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
