@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjliODQ3MzMzN2ZjMzhhMjkxMWRkZiIsImVtYWlsIjoiam9obkBlbWFpbC5jb20iLCJpYXQiOjE2NzMzNjA0MDUsImV4cCI6MTY3MzM2MDcwNX0.2ejMLl7_ky96Wf-bJGVRu7g6GJZn8O29ZX1qInuzbwo

###

# Get posts
GET http://localhost:3333/api/?sortByLikes=des&sortByPublish=asc HTTP/1.1
Content-Type: application/json

###

# Create text post
POST http://localhost:3333/api/text HTTP/1.1
Content-Type: application/json

{
  "creatorId": "63945562fd749e7b515950de",
  "title": "A progressive Node.js framework",
  "text": "A complete development kit for building scalable server-side apps. Contact us to find out more about expertise consulting, on-site enterprise support, trainings, and private sessions.",
  "previewText": "A complete development kit for building scalable server-side apps. Contact us..."
}

###

# Update text post
PATCH http://localhost:3333/api/text/1 HTTP/1.1
Content-Type: application/json

{
  "previewText": "A complete development kit for building scalable server-side apps. Contact us to find...",
  "tags": ["nextjs"]
}

###

# Create video post
POST http://localhost:3333/api/video HTTP/1.1
Content-Type: application/json

{
  "creatorId": "63945562fd749e7b515950de",
  "title": "NestJs JWT - Access Tokens & Refresh Tokens",
  "video": "https://www.youtube.com/watch?v=uAKzFhE3rxU"
}

###

# Update video post
PATCH http://localhost:3333/api/video/3 HTTP/1.1
Content-Type: application/json

{
  "title": "Holidays!!!",
  "video": "/posts/videos/ac623311-9728-4974-946e-0fb886e97fc5"
}

###

# Create photo post
POST http://localhost:3333/api/photo HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{accessToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="avatar.jpg"
Content-Type: image/jpg

< /mnt/f/assets/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Update photo post
PATCH http://localhost:3333/api/photo/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "tags": ["дорога", "город"],
  "book": "store"
}

###

# Create quote post
POST http://localhost:3333/api/quote HTTP/1.1
Content-Type: application/json

{
  "creatorId": "63945562fd749e7b515950de",
  "text": "With software there are only two possibilities: either the users control the programme or the programme controls the users. If the programme controls the users, and the developer controls the programme, then the programme is an instrument of unjust power.",
  "quoteAuthor": "Richard Stallman"
}

###

# Update quote post
PATCH http://localhost:3333/api/quote/2 HTTP/1.1
Content-Type: application/json

{
  "text": "With With software there are only two possibilities: either the users control the programme or the programme controls the users. If the programme controls the users, and the developer controls the programme, then the programme is an instrument of unjust power."
}

###

# Create link post
POST http://localhost:3333/api/link HTTP/1.1
Content-Type: application/json

{
  "creatorId": "63945562fd749e7b515950de",
  "link": "http://site.com/content/some-content",
  "description": "Информация о скидках"
}

###

# Update link post
PATCH http://localhost:3333/api/link/4 HTTP/1.1
Content-Type: application/json

{
  "link": "https://site.com/content/some-content",
  "description": "Информация о скидках"
}

###

# Delete post
DELETE http://localhost:3333/api/6 HTTP/1.1
Content-Type: application/json

###

# Repost post
POST http://localhost:3333/api/repost HTTP/1.1
Content-Type: application/json

{
  "postId": 2,
  "userId": "63945562fd749e7b515950de"
}

###

# Set like
POST http://localhost:3333/api/like/true HTTP/1.1
Content-Type: application/json

{
  "postId": 2,
  "userId": "63945562fd749e7b515950de"
}
