@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjliODQ3MzMzN2ZjMzhhMjkxMWRkZiIsImVtYWlsIjoiam9obkBlbWFpbC5jb20iLCJuYW1lIjoiSm9obiBDb25ub3IiLCJpYXQiOjE2NzM1NTUxNTksImV4cCI6MTY3MzU1NTQ1OX0.cgKHy_pfBfLfj0JJm6S5RdpxZD_OC7Q3eJx_HjnWEh4

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOTQ1NTYyZmQ3NDllN2I1MTU5NTBkZSIsImVtYWlsIjoiam9obkBlbWFpbC5jb20iLCJpYXQiOjE2NzI2Njc1ODQsImV4cCI6MTY3MzI3MjM4NH0.vkKo6Ng-fhsg5n6H3SOSvZl79INF07cSvjVC_4fcipU

###

# Create a new user
POST http://localhost:3334/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "john@email.com",
  "name": "John Connor",
  "password": "123456",
  "repeatedPassword": "123456"
}

###

# Upload avatar
POST http://localhost:3334/api/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{accessToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpg

< /mnt/f/assets/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Change password
POST http://localhost:3334/api/auth/change-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "654321",
  "newPassword": "123456"
}

###

# Login user
POST http://localhost:3334/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@email.com",
  "password": "123456"
}

###

# Refresh token
POST http://localhost:3334/api/auth/refresh HTTP/1.1
Authorization: Bearer {{refreshToken}}

###

# Get user
GET http://localhost:3334/api/auth/63b9b8473337fc38a2911ddf HTTP/1.1
